# Setup
title:               Dhan Vidya
tagline:             'Knowledge Investing'
description:         'Blog about finance, economics and many other things'
url:                 https://dhanvidya.github.io
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              Dhan Vidya
  url:               https://twitter.com/@DhanVidya
  email:             dhanvidya.guru@gmail.com

# Custom vars
version:             1.1.0
google_analytics_id: UA-165592418-1
